services:
    # PostgreSQL service for your app
    postgres:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: default
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        restart: always

    # TimescaleDB service for RIS Live data
    timescale:
        image: timescale/timescaledb:latest-pg13
        container_name: timescale
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: default
        ports:
            - "5433:5432"
        volumes:
            - timescale_data:/var/lib/postgresql/data
        restart: always

    # Flask application service
    web:
        build: .
        container_name: web
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        restart: always
        environment:
            - POSTGRESQL_DATABASE=postgresql://user:password@postgres:5432/default
            - TIMESCALE_DATABASE=postgresql://user:password@timescale:5432/default
            - POSTMARK_API_KEY=your-postmark-api-key
            - FLASK_SECRET_KEY=your-flask-secret-key
            - FLASK_HOST=http://localhost:5200
            - FLASK_ENV=development
            - FLASK_DEBUG=1
            - FLASK_APP=app.py
            - FLASK_RUN_PORT=5200
        ports:
            - "5200:5200"
        depends_on:
            - postgres
            - timescale
        working_dir: /app
        volumes:
            - .:/app
        entrypoint: gunicorn --bind 0.0.0.0:5200 --reload app:app

    # Independent data collector service for RIS Live data
    bgp_collector:
        build: .
        container_name: bgp_collector
        environment:
            - TIMESCALE_DATABASE=postgresql://user:password@timescale:5432/default
        depends_on:
            - timescale
        working_dir: /app
        volumes:
            - .:/app
        entrypoint: python collectors/bgp.py

# Define named volumes
volumes:
    pg_data:
    timescale_data:
