services:
    # PostgreSQL service
    postgres:
        image: timescale/timescaledb:latest-pg13
        container_name: postgres
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: default
        ports:
            - "5432:5432"
        volumes:
            - /Volumes/SDCARD/postgres_data:/var/lib/postgresql/data

    # Flask service
    web:
        build: .
        container_name: web
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        restart: always
        environment:
            - POSTGRESQL_DATABASE=postgresql+asyncpg://postgres:postgres@postgres:5432/default
            - POSTMARK_API_KEY=your-postmark-api-key
            - SECRET_KEY=your-flask-secret-key
            - ENVIRONMENT=development
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        working_dir: /app
        volumes:
            - .:/app
        entrypoint: >
            /bin/sh -c "alembic upgrade head && gunicorn --bind 0.0.0.0:8080 --workers 4 --worker-class uvicorn.workers.UvicornWorker --reload --log-level info --access-logfile - --error-logfile - 'app:asgi_app'"

    ####
    # RIS (Routing Information System) services
    #
    # These services collect and aggregate BGP routing data from RIPE NCC's RIS project.
    # They process real-time BGP updates, store them in the database, and provide
    # aggregated views of the global routing table.
    #
    # The 'ris' service connects to RIPE NCC's Kafka stream, processes BGP messages,
    # and stores them in the PostgreSQL database.
    #
    # The 'ris_peers' service periodically analyzes the collected data to identify
    # and categorize RIS peers, storing this information in Redis for quick access.
    ###
    ris:
        build: .
        container_name: ris
        environment:
            - POSTGRESQL_DATABASE=postgresql+asyncpg://postgres:postgres@postgres:5432/default
            - SASL_KAFKA_USERNAME=public
            - SASL_KAFKA_PASSWORD=public
        depends_on:
            web:
                condition: service_healthy
            postgres:
                condition: service_healthy
        working_dir: /app
        volumes:
            - .:/app
        entrypoint: >
            python services/ris.py

    ris_peers:
        build: .
        container_name: ris_peers
        environment:
            - POSTGRESQL_DATABASE=postgresql+asyncpg://postgres:postgres@postgres:5432/default
            - REDIS_DATABASE=redis://redis:6379
        depends_on:
            web:
                condition: service_healthy
            postgres:
                condition: service_healthy
        working_dir: /app
        volumes:
            - .:/app
        entrypoint: >
            python services/ris_peers.py

# Define volumes
volumes:
    pg_data:
