{{- define "openbmp_collectors_ris" -}}
{{- $values := .Values }}
{{- $collectors := "" -}}
{{- range $i, $openbmp := until (int $values.openbmp.collectors.hosts.ris.instances) -}}
  {{- $collectors = printf "%sopenbmp-collector-ris-%d:5000" $collectors $i -}}
  {{- if lt (add1 $i) (int $values.openbmp.collectors.hosts.ris.instances) -}}
    {{- $collectors = printf "%s," $collectors -}}
  {{- end -}}
{{- end -}}
{{- $collectors -}}
{{- end }}

{{- define "openbmp_collectors_routeviews" -}}
{{- $values := .Values }}
{{- $collectors := "" -}}
{{- range $i, $openbmp := until (int $values.openbmp.collectors.hosts.routeviews.instances) -}}
  {{- $collectors = printf "%sopenbmp-collector-routeviews-%d:5000" $collectors $i -}}
  {{- if lt (add1 $i) (int $values.openbmp.collectors.hosts.routeviews.instances) -}}
    {{- $collectors = printf "%s," $collectors -}}
  {{- end -}}
{{- end -}}
{{- $collectors -}}
{{- end }}

{{- $values := .Values }}

{{- range $index, $collector := $values.core.collectors.hosts.ris }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-collector-ris-{{ $collector.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-collector
      group: ris
      instance: {{ $collector.name }}
  template:
    metadata:
      labels:
        app: core-collector
        group: ris
        instance: {{ $collector.name }}
    spec:
      restartPolicy: Always
      containers:
      - name: core-collector
        image: bgpdata/bgpdata:{{ $.Chart.AppVersion }}
        command: ["python"]
        args: ["app.py", "--service", "collector"]
        resources:
          requests:
            cpu: {{ $values.core.collectors.resources.requests.cpu }}
            memory: {{ $values.core.collectors.resources.requests.memory }}
          limits:
            cpu: {{ $values.core.collectors.resources.limits.cpu }}
            memory: {{ $values.core.collectors.resources.limits.memory }}
        env:
        - name: POSTGRESQL_HOST
          value: "core-db"
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_USER
          value: "core"
        - name: POSTGRESQL_DB
          value: "default"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-db-secret
              key: password
        - name: OPENBMP_COLLECTORS
          value: {{ include "openbmp_collectors_ris" . }}
        - name: RIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: core-collector-secret-ris
              key: username
        - name: RIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-collector-secret-ris
              key: password
        - name: RIS_COLLECTORS
          value: {{ $collector.collectors }}
---
{{- end }}

{{- range $index, $collector := $values.core.collectors.hosts.routeviews }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-collector-routeviews-{{ $collector.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-collector
      group: route-views
      instance: {{ $collector.name }}
  template:
    metadata:
      labels:
        app: core-collector
        group: route-views
        instance: {{ $collector.name }}
    spec:
      containers:
      - name: core-collector
        image: bgpdata/bgpdata:{{ $.Chart.AppVersion }}
        command: ["python"]
        args: ["app.py", "--service", "collector"]
        resources:
          requests:
            cpu: {{ $values.core.collectors.resources.requests.cpu }}
            memory: {{ $values.core.collectors.resources.requests.memory }}
          limits:
            cpu: {{ $values.core.collectors.resources.limits.cpu }}
            memory: {{ $values.core.collectors.resources.limits.memory }}
        env:
        - name: POSTGRESQL_HOST
          value: "core-db"
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_USER
          value: "core"
        - name: POSTGRESQL_DB
          value: "default"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-db-secret
              key: password
        - name: OPENBMP_COLLECTORS
          value: {{ include "openbmp_collectors_routeviews" . }}
        - name: ROUTEVIEWS_USERNAME
          valueFrom:
            secretKeyRef:
              name: core-collector-secret-routeviews
              key: username
        - name: ROUTEVIEWS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-collector-secret-routeviews
              key: password
        - name: ROUTEVIEWS_COLLECTORS
          value: {{ $collector.collectors }}
---
{{- end }}