apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-web
spec:
  replicas: {{ .Values.core.web.replicas }}
  selector:
    matchLabels:
      app: core-web
  template:
    metadata:
      labels:
        app: core-web
    spec:
      restartPolicy: Always
      containers:
      - name: core-web
        image: bgpdata/bgpdata:{{ $.Chart.AppVersion }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            alembic upgrade head && \
            gunicorn --bind 0.0.0.0:8080 \
                    --workers 4 \
                    --worker-class uvicorn.workers.UvicornWorker \
                    --log-level info \
                    --access-logfile - \
                    --error-logfile - \
                    'app:asgi_app'
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 40  # this is the start_period
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: {{ .Values.core.web.resources.requests.cpu }}
            memory: {{ .Values.core.web.resources.requests.memory }}
          limits:
            cpu: {{ .Values.core.web.resources.limits.cpu }}
            memory: {{ .Values.core.web.resources.limits.memory }}
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESQL_HOST
          value: core-db
        - name: POSTGRESQL_PORT
          value: "5432"
        - name: POSTGRESQL_USER
          value: core
        - name: POSTGRESQL_DB
          value: default
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-db-secret
              key: password
      serviceAccountName: default
