{{- $root := . }}
{{- $values := .Values }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "bgpdata.fullname" . }}-core-collector
spec:
  serviceName: "{{ template "bgpdata.fullname" . }}-core-collector"
  replicas: {{ add (len .Values.core.collectors.hosts.ris) (len .Values.core.collectors.hosts.routeviews) }}
  selector:
    matchLabels:
      app: {{ template "bgpdata.fullname" . }}-core-collector
  template:
    metadata:
      labels:
        app: {{ template "bgpdata.fullname" . }}-core-collector
    spec:
      containers:
        {{- range $index, $collector := .Values.core.collectors.hosts.ris }}
        - name: {{ template "bgpdata.fullname" $root }}-core-collector-{{ $collector.name | replace "." "-" }}
          image: bgpdata/bgpdata:{{ $.Chart.AppVersion }}
          command: ["python"]
          args: ["app.py", "--service", "collector"]
          readinessProbe:
            exec:
              command: ["sh", "-c", "python3 -c 'import rocksdb; db = rocksdb.DB(\".rocksdb\", rocksdb.Options(create_if_missing=False)); exit(0) if db.get(b\"ready\") == b\"\\x01\" else exit(1)'"]
            periodSeconds: 60
            failureThreshold: 3
          env:
          - name: POSTGRESQL_HOST
            value: "{{ template "bgpdata.fullname" $root }}-core-db"
          - name: POSTGRESQL_PORT
            value: "5432"
          - name: POSTGRESQL_USER
            value: "core"
          - name: POSTGRESQL_DB
            value: "default"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "bgpdata.fullname" $root }}-core-db-secret
                key: password
          - name: OPENBMP_COLLECTORS
            value: "{{ template "bgpdata.fullname" $root }}-openbmp-collector-{{ $collector.name | replace "." "-" }}:5000"
          - name: RIS_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "bgpdata.fullname" $root }}-core-collector-secret-ris
                key: username
          - name: RIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "bgpdata.fullname" $root }}-core-collector-secret-ris
                key: password
          - name: RIS_COLLECTORS
            value: {{ $collector.collectors }}
          volumeMounts:
          - name: {{ template "bgpdata.fullname" $root }}-core-collector-{{ $collector.name | replace "." "-" }}
            mountPath: /app/.rocksdb
        {{- end }}

        {{- range $index, $collector := .Values.core.collectors.hosts.routeviews }}
        - name: {{ template "bgpdata.fullname" $root }}-core-collector-{{ $collector.name | replace "." "-" }}
          image: bgpdata/bgpdata:{{ $.Chart.AppVersion }}
          command: ["python"]
          args: ["app.py", "--service", "collector"]
          readinessProbe:
            exec:
              command: ["sh", "-c", "python3 -c 'import rocksdb; db = rocksdb.DB(\".rocksdb\", rocksdb.Options(create_if_missing=False)); exit(0) if db.get(b\"ready\") == b\"\\x01\" else exit(1)'"]
            periodSeconds: 60
            failureThreshold: 3
          env:
          - name: POSTGRESQL_HOST
            value: "{{ template "bgpdata.fullname" $root }}-core-db"
          - name: POSTGRESQL_PORT
            value: "5432"
          - name: POSTGRESQL_USER
            value: "core"
          - name: POSTGRESQL_DB
            value: "default"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "bgpdata.fullname" $root }}-core-db-secret
                key: password
          - name: OPENBMP_COLLECTORS
            value: "{{ template "bgpdata.fullname" $root }}-openbmp-collector-{{ $collector.name | replace "." "-" }}:5000"
          - name: ROUTEVIEWS_COLLECTORS
            value: {{ $collector.collectors }}
          volumeMounts:
          - name: {{ template "bgpdata.fullname" $root }}-core-collector-{{ $collector.name | replace "." "-" }}
            mountPath: /app/.rocksdb
        {{- end }}
  volumeClaimTemplates:
    {{- range $index, $collector := .Values.core.collectors.hosts.ris }}
    - metadata:
        name: {{ template "bgpdata.fullname" $root }}-core-collector-{{ $collector.name | replace "." "-" }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ $values.core.collectors.resources.storage.size }}
    {{- end }}

    {{- range $index, $collector := .Values.core.collectors.hosts.routeviews }}
    - metadata:
        name: {{ template "bgpdata.fullname" $root }}-core-collector-{{ $collector.name | replace "." "-" }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ $values.core.collectors.resources.storage.size }}
    {{- end }}