apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-collector-sa
  namespace: bgpdata
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-status-checker
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-core-collector-sa
  namespace: bgpdata
subjects:
  - kind: ServiceAccount
    name: core-collector-sa
    namespace: bgpdata
roleRef:
  kind: Role
  name: pod-status-checker
  apiGroup: rbac.authorization.k8s.io
