apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: core-db
spec:
  replicas: {{ .Values."core-services".database.replicas }}
  selector:
    matchLabels:
      app: core-db
  serviceName: core-db
  template:
    metadata:
      labels:
        app: core-db
    spec:
      restartPolicy: Always
      containers:
      - name: core-db
        image: timescale/timescaledb:latest-pg13
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - core
            - -d
            - default
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - core
            - -d
            - default
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        resources:
          requests:
            cpu: {{ .Values."core-services".database.resources.requests.cpu }}
            memory: {{ .Values."core-services".database.resources.requests.memory }}
          limits:
            cpu: {{ .Values."core-services".database.resources.limits.cpu }}
            memory: {{ .Values."core-services".database.resources.limits.memory }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "core"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-db-secret
              key: password
        - name: POSTGRES_DB
          value: "default"
        - name: PATRONI_SCOPE
          value: core-cluster
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_PORTS
          value: '[{"name": "postgresql", "port": 5432}]'
        volumeMounts:
        - name: core-db-data
          mountPath: /var/lib/postgresql/data
      initContainers:
      - name: install-patroni
        image: python:3.9-slim
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y python3-pip
          pip install patroni[kubernetes]
          cp -r /usr/local/lib/python3.9/site-packages/* /patroni-lib/
        volumeMounts:
        - name: patroni-lib
          mountPath: /patroni-lib
  volumeClaimTemplates:
  - metadata:
      name: core-db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values."core-services".database.resources.storage.size }}
  volumes:
  - name: patroni-lib
    emptyDir: {}
