apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "bgpdata.fullname" . }}-core-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: bgp-data.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "bgpdata.fullname" . }}-core-web
            port:
              number: 80
  tls:
  - hosts:
    - bgp-data.net
    secretName: {{ template "bgpdata.fullname" . }}-core-web-tls-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "bgpdata.fullname" . }}-openbmp-whois-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: whois.bgp-data.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "bgpdata.fullname" . }}-openbmp-whois
            port:
              number: 43
  tls:
  - hosts:
    - whois.bgp-data.net
    secretName: {{ template "bgpdata.fullname" . }}-openbmp-whois-tls-secret
