apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "bgpdata.fullname" . }}-openbmp-zookeeper
spec:
  replicas: {{ .Values.openbmp.kafka.zookeeper.replicas }}
  selector:
    matchLabels:
      app: {{ template "bgpdata.fullname" . }}-openbmp-zookeeper
  serviceName: {{ template "bgpdata.fullname" . }}-openbmp-zookeeper
  template:
    metadata:
      labels:
        app: {{ template "bgpdata.fullname" . }}-openbmp-zookeeper
    spec:
      restartPolicy: Always
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.7.1
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "10"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "5"
        resources:
          requests:
            cpu: {{ .Values.openbmp.kafka.zookeeper.resources.requests.cpu }}
            memory: {{ .Values.openbmp.kafka.zookeeper.resources.requests.memory }}
          limits:
            cpu: {{ .Values.openbmp.kafka.zookeeper.resources.limits.cpu }}
            memory: {{ .Values.openbmp.kafka.zookeeper.resources.limits.memory }}
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.openbmp.kafka.zookeeper.resources.storage.size }}
