{{- $root := . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "bgpdata.fullname" . }}-openbmp-collector
spec:
  serviceName: "{{ template "bgpdata.fullname" . }}-openbmp-collector"
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "bgpdata.fullname" . }}-openbmp-collector
  template:
    metadata:
      labels:
        app: {{ template "bgpdata.fullname" . }}-openbmp-collector
    spec:
      restartPolicy: Always
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_keepalive_intvl
          value: "30"
        - name: net.ipv4.tcp_keepalive_probes
          value: "5"
        - name: net.ipv4.tcp_keepalive_time
          value: "180"
      containers:
        {{- range $index, $collector := .Values.core.collectors.hosts.ris }}
        - name: {{ template "bgpdata.fullname" $root }}-openbmp-collector-{{ $collector.name | replace "." "-" }}
          image: openbmp/collector:2.2.3
          resources:
            requests:
              cpu: {{ $.Values.openbmp.collectors.resources.requests.cpu }}
              memory: {{ $.Values.openbmp.collectors.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.openbmp.collectors.resources.limits.cpu }}
              memory: {{ $.Values.openbmp.collectors.resources.limits.memory }}
          env:
          - name: KAFKA_FQDN
            value: "{{ template "bgpdata.fullname" $root }}-openbmp-kafka:29092"
          - name: UNIQUE_COLLECTOR
            value: {{ $collector.collectors }}
          livenessProbe:
            tcpSocket:
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
        {{- end }}

        {{- range $index, $collector := .Values.core.collectors.hosts.routeviews }}
        - name: {{ template "bgpdata.fullname" $root }}-openbmp-collector-{{ $collector.name | replace "." "-" }}
          image: openbmp/collector:2.2.3
          resources:
            requests:
              cpu: {{ $.Values.openbmp.collectors.resources.requests.cpu }}
              memory: {{ $.Values.openbmp.collectors.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.openbmp.collectors.resources.limits.cpu }}
              memory: {{ $.Values.openbmp.collectors.resources.limits.memory }}
          env:
          - name: KAFKA_FQDN
            value: "{{ template "bgpdata.fullname" $root }}-openbmp-kafka:29092"
          - name: UNIQUE_COLLECTOR
            value: {{ $collector.collectors }}
          livenessProbe:
            tcpSocket:
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
        {{- end }}