apiVersion: v1
kind: Service
metadata:
  name: core-web-service
spec:
  type: LoadBalancer
  selector:
    app: core-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
{{- range $i, $openbmp := until (int .Values.openbmp.collectors.hosts.routeviews.instances) }}
apiVersion: v1
kind: Service
metadata:
  name: openbmp-collector-routeviews-{{ $i }}-service
spec:
  clusterIP: None
  selector:
    app: openbmp-collector
    group: routeviews
    instance: routeviews-{{ $i }}
{{- end }}
---
{{- range $i, $openbmp := until (int .Values.openbmp.collectors.hosts.ris.instances) }}
apiVersion: v1
kind: Service
metadata:
  name: openbmp-collector-ris-{{ $i }}-service
spec:
  clusterIP: None
  selector:
    app: openbmp-collector
    group: ris
    instance: ris-{{ $i }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: openbmp-db-service
spec:
  type: ClusterIP
  selector:
    app: openbmp-db
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: openbmp-kafka-service
spec:
  clusterIP: None
  selector:
    app: openbmp-kafka
  ports:
  - name: broker
    port: 29092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: openbmp-zookeeper-service
spec:
  clusterIP: None
  selector:
    app: openbmp-zookeeper
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  - name: peer
    port: 2888
    targetPort: 2888
  - name: leader-election
    port: 3888
    targetPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: openbmp-whois-service
spec:
  type: LoadBalancer
  selector:
    app: openbmp-whois
  ports:
  - protocol: TCP
    port: 43
    targetPort: 43