{{- $root := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bgpdata.fullname" . }}-core-web-service
spec:
  type: LoadBalancer
  selector:
    app: {{ template "bgpdata.fullname" . }}-core-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
{{- range $i, $openbmp := until (int .Values.openbmp.collectors.hosts.routeviews.instances) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bgpdata.fullname" $root }}-openbmp-collector-routeviews-{{ $i }}-service
spec:
  clusterIP: None
  selector:
    app: {{ template "bgpdata.fullname" $root }}-openbmp-collector
    instance: routeviews-{{ $i }}
{{- end }}
---
{{- range $i, $openbmp := until (int .Values.openbmp.collectors.hosts.ris.instances) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bgpdata.fullname" $root }}-openbmp-collector-ris-{{ $i }}-service
spec:
  clusterIP: None
  selector:
    app: {{ template "bgpdata.fullname" $root }}-openbmp-collector
    instance: ris-{{ $i }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bgpdata.fullname" . }}-openbmp-db-service
spec:
  type: ClusterIP
  selector:
    app: {{ template "bgpdata.fullname" . }}-openbmp-db
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bgpdata.fullname" . }}-openbmp-kafka-service
spec:
  clusterIP: None
  selector:
    app: {{ template "bgpdata.fullname" . }}-openbmp-kafka
  ports:
  - name: broker
    port: 29092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bgpdata.fullname" . }}-openbmp-zookeeper-service
spec:
  clusterIP: None
  selector:
    app: {{ template "bgpdata.fullname" . }}-openbmp-zookeeper
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  - name: peer
    port: 2888
    targetPort: 2888
  - name: leader-election
    port: 3888
    targetPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bgpdata.fullname" . }}-openbmp-whois-service
spec:
  type: LoadBalancer
  selector:
    app: {{ template "bgpdata.fullname" . }}-openbmp-whois
  ports:
  - protocol: TCP
    port: 43
    targetPort: 43