core:
  web:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  collectors:
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
      storage:
        size: "100Mi"
    hosts:
      ris:
        - name: rrc00.ripe.net
          collectors: "rrc00"
      routeviews:
        - name: amsix.ams.routeviews.org
          collectors: "amsix.ams:293"
  database:
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
      storage:
        size: "2Gi"

openbmp:
  app:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  collectors:
    resources:
        requests:
          cpu: "500m"
          memory: "3Gi"
        limits:
          cpu: "1"
          memory: "4Gi"
  database:
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "4Gi"
      storage:
        size: "40Gi"
  kafka:
    zookeeper:
      replicas: 1
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
        storage:
          size: "5Gi"
    kafka:
      replicas: 1
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "4Gi"
        storage:
          size: "4Gi"
  whois:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
