core:
  web:
    replicas: 3
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  collectors:
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
      storage:
        size: "100Mi"
    secrets:
      ris:
        username: "public"
        password: "public"
      routeviews:
        username: "public"
        password: "public"
    hosts:
      ris:
        - name: rrc00.ripe.net
          collectors: "rrc00"
        - name: rrc01.ripe.net
          collectors: "rrc01"
        - name: rrc03.ripe.net
          collectors: "rrc03"
        - name: rrc04.ripe.net
          collectors: "rrc04"
        - name: rrc05.ripe.net
          collectors: "rrc05"
        - name: rrc06.ripe.net
          collectors: "rrc06"
        - name: rrc07.ripe.net
          collectors: "rrc07"
        - name: rrc10.ripe.net
          collectors: "rrc10"
        - name: rrc11.ripe.net
          collectors: "rrc11"
        - name: rrc12.ripe.net
          collectors: "rrc12"
        - name: rrc13.ripe.net
          collectors: "rrc13"
        - name: rrc14.ripe.net
          collectors: "rrc14"
        - name: rrc15.ripe.net
          collectors: "rrc15"
        - name: rrc16.ripe.net
          collectors: "rrc16"
        - name: rrc18.ripe.net
          collectors: "rrc18"
        - name: rrc19.ripe.net
          collectors: "rrc19"
        - name: rrc20.ripe.net
          collectors: "rrc20"
        - name: rrc21.ripe.net
          collectors: "rrc21"
        - name: rrc22.ripe.net
          collectors: "rrc22"
        - name: rrc23.ripe.net
          collectors: "rrc23"
        - name: rrc24.ripe.net
          collectors: "rrc24"
        - name: rrc25.ripe.net
          collectors: "rrc25"
        - name: rrc26.ripe.net
          collectors: "rrc26"
      routeviews:
        - name: amsix.ams.routeviews.org
          collectors: "amsix.ams:293,amsix.ams:1103,amsix.ams:1140,amsix.ams:3320,amsix.ams:6204,amsix.ams:6777,amsix.ams:20253,amsix.ams:28283,amsix.ams:34177,amsix.ams:37271,amsix.ams:39120,amsix.ams:49544,amsix.ams:56987,amsix.ams:213241,amsix.ams:271253,amsix.ams:328832,amsix.ams:398465"
        - name: route-views.amsix.routeviews.org
          collectors: "amsix:1103,amsix:3214,amsix:3399,amsix:6762,amsix:6830,amsix:8888,amsix:9002,amsix:12779,amsix:12859,amsix:16509,amsix:16552,amsix:30844,amsix:38880,amsix:39591,amsix:42541,amsix:44324,amsix:47957,amsix:50763,amsix:51019,amsix:51088,amsix:56662,amsix:58511,amsix:60144,amsix:60150,amsix:61955,amsix:199524,amsix:200242,amsix:208753,amsix:211398,amsix:213151,amsix:216311,amsix:267613"
        - name: route-views.bknix.routeviews.org
          collectors: "bknix:59238,bknix:63529"
        - name: route-views.chicago.routeviews.org
          collectors: "chicago:293,chicago:852,chicago:3257,chicago:8220,chicago:14630,chicago:16509,chicago:16552,chicago:17350,chicago:19151,chicago:19653,chicago:20253,chicago:24115,chicago:32709,chicago:49544,chicago:53828,chicago:199524,chicago:398465"
        - name: route-views.chile.routeviews.org
          collectors: "chile:27678,chile:27986"
        - name: cix.atl.routeviews.org
          collectors: "cix.atl:13335,cix.atl:16509,cix.atl:20253,cix.atl:20940,cix.atl:63221"
        - name: decix.jhb.routeviews.org
          collectors: "decix.jhb:16509,decix.jhb:38137,decix.jhb:38194,decix.jhb:199524"
        - name: route-views.eqix.routeviews.org
          collectors: "eqix:293,eqix:2914,eqix:3257,eqix:3320,eqix:6057,eqix:6079,eqix:6762,eqix:6830,eqix:6939,eqix:8220,eqix:8781,eqix:11039,eqix:16509,eqix:16552,eqix:17350,eqix:19151,eqix:20253,eqix:32098,eqix:37468,eqix:37721,eqix:40934,eqix:41095,eqix:49544,eqix:57695,eqix:199524,eqix:398465"
        - name: route-views.flix.routeviews.org
          collectors: "flix:1031,flix:6939,flix:7195,flix:15280,flix:16509,flix:16552,flix:19151,flix:20253,flix:28283,flix:52320,flix:52468,flix:63221,flix:263237,flix:264409"
        - name: route-views.fortaleza.routeviews.org
          collectors: "fortaleza:1031,fortaleza:20253,fortaleza:26162,fortaleza:28624,fortaleza:52320,fortaleza:199524,fortaleza:262462,fortaleza:263945,fortaleza:264409,fortaleza:264479"
        - name: route-views.gorex.routeviews.org
          collectors: "gorex:16509,gorex:40300,gorex:65534"
        - name: route-views.isc.routeviews.org
          collectors: "isc:3320,isc:6762,isc:6939,isc:7575,isc:16509,isc:19151,isc:49544,isc:199524"
        - name: route-views.kixp.routeviews.org
          collectors: "kixp:6939,kixp:16509,kixp:37271,kixp:37704,kixp:63293,kixp:328475,kixp:328977"
        - name: route-views.linx.routeviews.org
          collectors: "linx:1031,linx:2914,linx:3170,linx:3257,linx:3491,linx:5413,linx:5511,linx:6424,linx:6453,linx:6667,linx:6762,linx:6830,linx:6939,linx:8455,linx:8714,linx:9002,linx:13030,linx:13237,linx:14537,linx:16509,linx:16552,linx:31500,linx:34288,linx:37271,linx:38182,linx:38880,linx:39122,linx:41811,linx:47957,linx:48070,linx:49544,linx:58511,linx:59605,linx:267613,linx:398465"
        - name: route-views.napafrica.routeviews.org
          collectors: "napafrica:3491,napafrica:16509,napafrica:16552,napafrica:32653,napafrica:37271,napafrica:37468,napafrica:49544,napafrica:199524,napafrica:328137,napafrica:328206,napafrica:328266,napafrica:328320,napafrica:328512,napafrica:328964,napafrica:329035"
        - name: route-views.ny.routeviews.org
          collectors: "ny:11399,ny:13335,ny:20253,ny:20940,ny:28213,ny:32934,ny:49544,ny:63034,ny:64289,ny:398465"
        - name: route-views.perth.routeviews.org
          collectors: "perth:7594,perth:7606,perth:17766,perth:49544,perth:58511,perth:136557,perth:140627,perth:199524"
        - name: route-views.rio.routeviews.org
          collectors: "rio:999,rio:1031,rio:6057,rio:20253,rio:26162,rio:52320,rio:52468,rio:199524,rio:264409,rio:264479,rio:267613"
        - name: route-views2.saopaulo.routeviews.org
          collectors: "route-views2.saopaulo:1031,route-views2.saopaulo:7195,route-views2.saopaulo:13786,route-views2.saopaulo:16552,route-views2.saopaulo:26162,route-views2.saopaulo:28329,route-views2.saopaulo:37468,route-views2.saopaulo:49544,route-views2.saopaulo:52468,route-views2.saopaulo:52863,route-views2.saopaulo:52873,route-views2.saopaulo:60503,route-views2.saopaulo:61832,route-views2.saopaulo:199524,route-views2.saopaulo:262791,route-views2.saopaulo:263009,route-views2.saopaulo:263237,route-views2.saopaulo:263541,route-views2.saopaulo:264409,route-views2.saopaulo:264479,route-views2.saopaulo:268976,route-views2.saopaulo:271253"
        - name: route-views3.routeviews.org
          collectors: "route-views3:209,route-views3:3216,route-views3:3257,route-views3:3561,route-views3:5645,route-views3:6939,route-views3:8289,route-views3:9268,route-views3:11537,route-views3:14315,route-views3:19653,route-views3:22388,route-views3:23367,route-views3:29479,route-views3:38001,route-views3:38136,route-views3:39120,route-views3:40387,route-views3:45352,route-views3:46450,route-views3:55222,route-views3:61568,route-views3:63927,route-views3:202365"
        - name: route-views4.routeviews.org
          collectors: "route-views4:1299,route-views4:1351,route-views4:2518,route-views4:2914,route-views4:14041,route-views4:19754,route-views4:19782,route-views4:24482,route-views4:30950,route-views4:32653,route-views4:34288,route-views4:36236,route-views4:38726,route-views4:38883,route-views4:45437,route-views4:56665,route-views4:57050,route-views4:58511,route-views4:58682,route-views4:63956,route-views4:133950,route-views4:204028"
        - name: route-views5.routeviews.org
          collectors: "route-views5:955,route-views5:1221,route-views5:11537,route-views5:13058,route-views5:19529,route-views5:22296,route-views5:33185,route-views5:37721,route-views5:41666,route-views5:49544,route-views5:56987,route-views5:58511,route-views5:60539,route-views5:132884,route-views5:137409,route-views5:199518,route-views5:207934,route-views5:208594"
        - name: route-views6.routeviews.org
          collectors: "route-views6:209,route-views6:701,route-views6:1403,route-views6:2497,route-views6:2914,route-views6:3130,route-views6:3257,route-views6:6939,route-views6:7018,route-views6:7660,route-views6:18106,route-views6:20130,route-views6:20912,route-views6:22652,route-views6:23673,route-views6:37100,route-views6:49788,route-views6:57463,route-views6:57866,route-views6:58511,route-views6:140731,route-views6:209306"
        - name: route-views7.routeviews.org
          collectors: "route-views7:260,route-views7:924,route-views7:4641,route-views7:5580,route-views7:8582,route-views7:16260,route-views7:30371,route-views7:37989,route-views7:40864,route-views7:44620,route-views7:44901,route-views7:48297,route-views7:51999,route-views7:57344,route-views7:132213,route-views7:150369,route-views7:199310,route-views7:206271,route-views7:328977,route-views7:401021"
        - name: route-views.routeviews.org
          collectors: "route-views:101,route-views:3333,route-views:4901,route-views:20080,route-views:57866"
        - name: route-views.sfmix.routeviews.org
          collectors: "sfmix:16509,sfmix:20253,sfmix:34927,sfmix:35008,sfmix:49544,sfmix:63055,sfmix:64289,sfmix:397131"
        - name: route-views.sg.routeviews.org
          collectors: "sg:3491,sg:4637,sg:6762,sg:7713,sg:8220,sg:9002,sg:9902,sg:16509,sg:16552,sg:17660,sg:18106,sg:24115,sg:24482,sg:24516,sg:37468,sg:38182,sg:38880,sg:49544,sg:58511,sg:58952,sg:59318,sg:63927,sg:132337,sg:136106,sg:136557,sg:151326,sg:199524"
        - name: route-views.soxrs.routeviews.org
          collectors: "soxrs:13004,soxrs:199524"
        - name: route-views.sydney.routeviews.org
          collectors: "sydney:3491,sydney:4826,sydney:7575,sydney:7594,sydney:8888,sydney:9266,sydney:16552,sydney:24115,sydney:24516,sydney:58511,sydney:63956,sydney:132847,sydney:135895,sydney:148968,sydney:199524,sydney:398465"
        - name: route-views.telxatl.routeviews.org
          collectors: "telxatl:4181,telxatl:6082,telxatl:6939,telxatl:16509,telxatl:19151,telxatl:20253,telxatl:32299,telxatl:53828"
        - name: route-views.uaeix.routeviews.org
          collectors: "uaeix:16509,uaeix:42473,uaeix:49544,uaeix:60924,uaeix:61374,uaeix:199524"
        - name: route-views.wide.routeviews.org
          collectors: "wide:2497,wide:2500,wide:2516,wide:7500"
  database:
    password: "your-super-secret-password"
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "4Gi"
      storage:
        size: "250Gi"

openbmp:
  app:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  collectors:
    resources:
        requests:
          cpu: "500m"
          memory: "3Gi"
        limits:
          cpu: "1"
          memory: "4Gi"
  database:
    password: "your-super-secret-password"
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "4Gi"
      storage:
        size: "2048Gi"
  kafka:
    zookeeper:
      replicas: 3
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
        storage:
          size: "10Gi"
    kafka:
      replicas: 3
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "8Gi"
        storage:
          size: "100Gi"
  whois:
    replicas: 3
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
